### ISSUE TITLE
Add Comic

### ISSUE THREAD

**Issue by fangohr** [bossee-project/proposal#35]
This [1] is a nice starting point to explain where we are coming from:

the comic illustrates the current state of the art prototype workflow, partly achieved with the OpenDreamKit project, which has overlap with some of the partners in this project.

In this project, we want to make this process more reproducible for the future, more flexible and improve several other components of the ecosystem that allow this.

Should be mentioned somewhere in the first few pages? Could also go to the impact section - there we haven't got much material yet, and we could use the comic as an illustration for what the impact of the project could look like, and that it is broadly applicable across many domains. [Maybe that's better?].

[1] https://opendreamkit.org/public/images/use-cases-binder-logbook-solution.png

**Comment by minrk** [comment]
Great idea. What's the proper credit for the image? I can add it.

**Comment by nthiery** [comment]
>    Great idea. What's the proper credit for the image? I can add it.

Juliette Belin, funded by ODK at Logilab.

Cheers,
		Nicolas
--
Nicolas M. Thiéry "Isil" <nthiery@users.sf.net>
http://Nicolas.Thiery.name/

**Comment by minrk** [comment]
@nthiery thanks! And the copyright on the image?

**Comment by fangohr** [comment]
... good question. We should be okay to use it as it was funded by ODK. I don't know if a particular license was agreed.

**Comment by nthiery** [comment]
>    [1]https://twitter.com/JulietteTaka/status/1082695675945598977 is what
>    she said about licensing.

Yep. CC-BY-SA

**Comment by takluyver** [comment]
I've added this as a figure in the impact section, in commit 2b7a3271511c689e30ce5b12e1347858926ffb33. Feel free to update the caption if we need to present any other information for copyright.
