### ISSUE TITLE
Show example of notebook somewhere

### ISSUE THREAD

**Issue by fangohr** [bossee-project/proposal#36]
It would be good to have an example of a notebook somewhere. 

Let's assume a reviewer doesn't know what it is, then this will be very useful.

Who has an example ready or can produce one? The challenge is to show key features on little space. We'd also need a paragraph or two of explanation.

**Comment by nthiery** [comment]
>    It would be good to have an example of a notebook somewhere.
> 
>    Let's assume a reviewer doesn't know what it is, then this will be very
>    useful.

Yes it would be very good to have a few, displaying the wide range of
usage, from simple computation session with visualization to
applet/dashboards via interactive books / exercise sheets.

>    Who has an example ready or can produce one? The challenge is to
>    show key features on little space. We'd also need a paragraph or
>    two of explanation.

We had one (or a few?) in ODK's proposal. We also have a bunch in our
various deliverable reports. See e.g. p. 3 of:

        https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP4/D4.16/report-final.pdf

or p. 7- of https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP4/D4.12/report-final.pdf

        https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP4/D4.12/report-final.pdf

Cheers,

**Comment by annefou** [comment]
along the same lines, it may be useful to define "Jupyter ecosystem"; just to make sure everybody has the same definition (google search on my laptop does not show much with "jupyter ecosystem").

**Comment by minrk** [comment]
Great points!

**Comment by takluyver** [comment]
There is now a screenshot of an example notebook in section 1.2, along with more description of what the Jupyter Notebook and the Jupyter ecosystem consist of. Accordingly, I'm going to close this issue.
Of course, if this isn't what people were thinking of, we can always reopen it, or create a new issue.
