### ISSUE TITLE
Define and share the aims and objectives

### ISSUE THREAD

**Issue by nthiery** [bossee-project/proposal#4]
The aims should give in just a few words an overview of the project: motivation, strategy, and how it all ties into the call.

Here is a first attempt:

https://github.com/bossee-project/proposal/blob/35544191b746e915ae2bb0ec73c3c08b0f87688c/objectives.tex#L12-L26

**Comment by minrk** [comment]
That's a great start. The gist from my point of view:

1. develop and support the Jupyter ecosystem in a direction that benefits and facilitates open science
2. make these tools accessible to as many people as possible via operation of free, public services
3. demonstrate and ensure that these developments are useful to real scientists and the public 
4. foster open science through training of students and researchers in best practices using these tools

**Comment by pdehaye** [comment]
Remark: In some situations (like personal data), the science comes later, aggregating data from many sources, but is facilitated if early on Jupyter is already used (by activists, journalists, etc)

**Comment by nthiery** [comment]
The above aims have evolved into a nice list of objectives in the proposal. But we have no aims any more. Do we want to reintroduce them? I believe they were a nice way to briefly expose the concept behind the project. And also a nice benchmark against which to justify actions (e.g. when we describe our KPI's).

**Comment by annefou** [comment]
Yes I think a few overall goals should be added before giving a detailed list of objectives. Some objectives (for instance objective 7) gives the feeling you will not be able to provide operational EOSC services at the end of the project (pilot MyBinder). 
You should show you are able to provide a pilot MyBinder on EOSC at the very beginning of the project (M6), isn't it?
Relation to the work programme is missing too.

**Comment by fangohr** [comment]
Many discussions and refinements. This is now done.
