### ISSUE TITLE
Project management and structure

### ISSUE THREAD

**Issue by nthiery** [bossee-project/proposal#40]
cc: @minrk, @fangohr 

As planned, I have imported the management structure section from ODK, and adapted it (including the picture). Please review!

There are some TODO's here and there. Major point to check:
- are end users sufficiently represented?
- I haven't touched the risk management section; are there things to update there w.r.t. ODK?
- Hans: I specified that you would be the Project Deputy (which in practice you have been in the preparation :-) ). Is that ok with you?

**Comment by fangohr** [comment]
Only saw the message now - no problem with deputy role.

**Comment by nthiery** [comment]
>    Only saw the message now - no problem with deputy role.

Congratulations :-)
