### ISSUE TITLE
Add a direct link from the README to the latest pdf produced by continuous integration

### ISSUE THREAD

**Issue by nthiery** [bossee-project/proposal#5]
For very quick access. But also because I actually myself failed to access the pdf :-); there was no "Artifact" tab when I went to CircleCI. Maybe because I was not logged in?

**Comment by minrk** [comment]
The url is like `https://circleci.com/gh/bossee-project/proposal/24#artifacts/containers/0` where `24` is replaced with the latest build. Unfortunately, there doesn't appear to be any link that points to 'latest' without clicking through circle, so the instructions given appear to be the best we can do:

1. click the circle badge in the README
2. click the latest build
3. click Artifacts
4. click draft.pdf

**Comment by minrk** [comment]
Did the best I could do in the README, which is a link that contains a single URL that you can follow.
