### ISSUE TITLE
Standardize wp/task/deliverable labels

### ISSUE THREAD

**Issue by nthiery** [bossee-project/proposal#51]
In ODK we have not been very good at choosing good latex labels for our tasks & such, which always made it a pain to remember/retrieve them. We could try to aim for some better consistency, starting with ensuring the following schemes:
- the latex label, filename, and reference in the spreadsheet for a wp/task/site should be identical
- ???

Should we try to do this now? Or is this to disruptive at this stage where we are all editing simultaneously? We could also do it after the proposal is accepted. If it is ...
cc: @fangohr, @minrk

**Comment by minrk** [comment]
The spreadsheet should be mostly done with its service on tasks and WPs. The only information that should be relevant in the spreadsheet now is total PMs per site.

If it helps to make things consistent, we can reorganize a little bit, but that might be more disruptive than it's worth to others who are working on those files.

**Comment by fangohr** [comment]
I'll close the issue so we can focus on open ones in the hectic period now.
