### ISSUE TITLE
Re-review abstract

### ISSUE THREAD

**Issue by fangohr** [bossee-project/proposal#59]
I wrote the abstract a looooong time ago. It should be reviewed based on the actual proposal.

We may also want to remove the reference to PaNOSC - we have much more evidence of Jupyter use the case, so I don't think it necessarily strengthens the case here.

**Comment by minrk** [comment]
I gave the abstract a pass based on updated contents. I did leave the reference to PaNOSC, since it ties specifically to EOSC, not just wide adoption in general.

**Comment by fangohr** [comment]
Closed today on Slack.
