### ISSUE TITLE
Third parties: CNRS ?

### ISSUE THREAD

**Issue by gouarin** [bossee-project/proposal#64]
Do we have to add the CNRS as a third party in section 4.2 ? If yes, here is a description text

LINK OF THE PARTICIPANT OT THE THIRD PARTY
The CNRS, “Centre National de la Recherche Scientifique” (National Center 
for Scientific Research) will be a linked third party of École Polytechnique 
in the framework of a Joint Research Unit agreement (Centre de Mathematiques 
Appliquées, CMAP). The CMAP Joint Research Unit legally links the parties, 
which have long-standing collaborations well beyond the BOSSEE project, and 
therefore fulfil all requirements in Article 14 of the Model Grant Agreement 
to be considered linked third parties.

LINKED THIRD PARTY DESCRIPTION
The CNRS is a public organization under the responsibility of the French 
Ministry of Higher Education and Research. As the largest fundamental 
research organization in Europe, CNRS carried out research in all fields of 
knowledge, including the humanities and social sciences, biological 
sciences, nuclear and particle physics, information sciences, engineering 
and systems, physics, mathematical sciences, chemistry, earth sciences and 
astronomy, ecology and the environment. CNRS encourages collaboration 
between specialists from different disciplines in particular with the 
university thus opening up new fields of enquiry to meet social and economic 
needs. With 34,000 researchers, engineers and technicians, CNRS is organized 
around 10 institutes which orchestrate its scientific policy. CNRS has a 
budget of approximately €3.3 billion. Its 1,053 laboratories, including 95% 
in partnership with universities, higher-education institutions and other 
research organizations, are present throughout France.

**Comment by minrk** [comment]
CNRS would be a third party if it is a subcontractor receiving money paid directly to another partner. Is this the case? I don't see any mention of such a thing.

**Comment by gouarin** [comment]
@minrk finally it's not necessary to add CNRS as a third party. I just have to add CNRS for EP somewhere.
