### ISSUE TITLE
"Open Science" or "open science"

### ISSUE THREAD

**Issue by embray** [bossee-project/proposal#76]
Throughout much of the proposal the term "Open Science" is capitalized, I suppose, in order to give the term extra weight.

However, there are some places where it is not capitalized.  For stylistic consistency perhaps most of those cases should be changed to "Open Science" as well?

**Comment by minrk** [comment]
We had this discussion, and since it's an EU funding keyword and the main goal of the funding call, we were treating it as a proper noun. I guess not quite consistently. I did periodic find/replaces, but forgot to do one last one.
